### PR TITLE
Added a guide for syntax highlighting (and more) in Vim 

### PR DESCRIPTION
**Pull request by zaxioms0**
A lot of people have asked me how I make my Vim look nice when writing SML so I added a little guide. Hopefully this is useful :D

### CODE REVIEW

**Comment by T-Brick** [comment]
consider not using vim : )

**Comment by zaxioms0** [comment]
:sob: (for the record figuring out how to install the VSCode plugin so I could add it to the guide took me longer than writing the entire guide for Vim hehe :flushed:)

**Comment by zaxioms0** [comment]
Oh oops bad commit name lol! It addresses the first of Issue #57

**Comment by zaxioms0** [comment]
I'm going to uncommit the changes to #57 and instead put them in a new branch (at #60 now)

**Review by kevinazhou150 — APPROVED** [review]
looks good!

**Pull request merged**
